# Generated by Django 4.2.5 on 2023-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyectocrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ent', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('fecha_sal', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
